### ISSUE TITLE
Flash::overlay() message for compability with laracasts/flash

### ISSUE THREAD

**Issue by KIVagant** [skrajewski/laravel-flash-notifications#4]
Some popular laravel packages have dependencies with laracasts/flash. For example, [mitul/laravel-api-generator](https://github.com/mitulgolakiya/laravel-api-generator)
Can you add a Flash::overlay() method for compability with third-party packages?
Your package looks more clear, unlike laracasts variant.

Thank you.

**Comment by skrajewski** [comment]
Hello @KIVagant,

Thank you. I want to keep this package simple as possible - I think the _Flash::overlay_ method is like _Flash::info with different layout. I can create this additional method, but maybe it's not necessary?  

Kind Regards,
Szymon

**Comment by KIVagant** [comment]
Good evening, @skrajewski .

I like your package because of simplicity. 
I thought about this problem. Of course, you do not have to make support of external package. I created the SzykraToLaracastsWrapperProvider temporally and it's really mitul/api-generator problem with bad dependencies.
[This issue](https://github.com/mitulgolakiya/laravel-api-generator/issues/43) in laravel-api-generator about using laracasts/flash more logical than issue in your package.

So, you should close this topic.

**Comment by KIVagant** [comment]
I made a [fix for api-generator](https://github.com/mitulgolakiya/laravel-api-generator/pull/45). Issue is not actial.
