### ISSUE TITLE
Not working in Laravel 5.2

### ISSUE THREAD

**Issue by pawlakzn** [skrajewski/laravel-flash-notifications#6]
Call to undefined method Illuminate\Foundation\Application::bindShared()

You need to change it to singletion(). It's required by Laravel 5.2.

Cheers!

**Comment by skrajewski** [comment]
Thanks @pawlakzn , fix is available in version 0.3.3 505074ee40e4ddfb715c9d4efe83485038f720a8

Kind Regards,
Szymon
